name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: latest
        project_id: ${{ secrets.GOOGLE_PROJECT }}
       
 
    - name: Authenticate to GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > "${HOME}/gcloud-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcloud-key.json"
        gcloud config set project ${{ secrets.GOOGLE_PROJECT }}


    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-southwest1-docker.pkg.dev
        docker build -t europe-southwest1-docker.pkg.dev/model-academy-423510-m6/demo/nginx:latest .
        docker push europe-southwest1-docker.pkg.dev/model-academy-423510-m6/demo/nginx:latest

        